### ISSUE TITLE
crash du serveur dûe au tortues 

### ISSUE THREAD

**Issue by matt8fr** [sys4-fr/server-nalc#15]
un clique droit sur une tortue a fait planter le serveur

**Comment by sys4-fr** [comment]
Bien vue :)
C'était un appel vers une fonction qui n'existait pas (set_velocity).
J'ai donc créé la fonction manquante en recopiant celle du fichier api.lua du mod mobs.
Cette fonction permet d'arrêter un mob dans sa marche.
Pour la tortue, quand on clique droit dessus, elle s'arrête et se cache dans sa carapace pendant 5 secondes.
J'ai vérifié pour les autres mobs, apparemment ce bug n'affectait que la tortue.
Merci.
