### ISSUE TITLE
Régler le problème des tartes qui ne se craftent pas à partir des baies

### ISSUE THREAD

**Issue by sys4-fr** [sys4-fr/server-nalc#24]
Cela est certainement du au chevauchement des mod bushes_classic et farming redo.

**Comment by Grossam** [comment]
C'est au niveau des Blueberry et des Raspwberry. Pour unifier, les buissons fournissent des farming_redo:blackberry et des farming_redo:rasberry qui n'appartiennent pas au groupe Berry et ne sont pas prises en compte par les recettes de bush_classic. Enfin je suppose.

Du coup, comme tu disais, on peut faire des alias, mais dans ce cas, ce sont les recettes de farming_redo qui ne vont plus marcher ?

**Comment by Grossam** [comment]
Vérification faite : bush_classic semble prendre le problème en compte dans cooking.lua à partir de la ligne 40.

Bizarre que ça ne marche pas ? Ton mod est à jour ?

**Comment by sys4-fr** [comment]
Le mod bushes_classic fait parti du submodule plantlife_modpack qui pointe vers le repository officiel. Donc il est à jour.

Par contre farming (redo) est un submodule vers un repository que j'ai forké. Donc je peux le mettre à jour, puis si ça ne suffit pas, on peut tenter de corriger ce problème dans mon fork. Et éventuellement proposer un PR à TenPlus1.

Ou autre solution, faire la correction si c'est possible, depuis le mod nalc.
A suivre...

**Comment by sys4-fr** [comment]
Résolue en updatant le mod morefarming qui supprimait le groupe berry des berries. Maintenant les groupes de morefarming sont rajoutés au lieu de remplacer tout les groupes précédents.
